### ISSUE TITLE
`.onInvalid()` doesn't get called when `.checkValidity()` is native

### ISSUE THREAD

**Issue by leonsas** [ryanseddon/H5F#64]
on Safari 8, there are no validation errors displayed natively, so I would like to use the `onInvalid` helped to create some, but `onInvalid` is never called as Safari forms do have `.checkValidity`

**Comment by silenceisgolden** [comment]
It would be nice to have onInvalid called each time the input is validated with the result of that being invalid.

**Comment by mickeyhead7** [comment]
+1 The invalid event gets fired natively in modern supported browsers (e.g. Chrome, Firefox, etc) when `checkValidity()` is called. This does not happen with the polyfill in older unsupported browsers (e.g. IE9).

The problem is that these browsers also do not support firing a `CustomEvent` either to polyfill this, so a solution such as [custom-event-polyfill](https://www.npmjs.com/package/custom-event-polyfill) is also required.
